apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: pi-agent-rolebinding
 namespace: pi-agent
subjects:
 - kind: ServiceAccount
   name: pi-agnet-sa
   namespace: pi-agent
roleRef:
 kind: Role
 name: pi-agent-role
 apiGroups: rbac.authorization.k8s.io